"""Render ODD protocol reports as canonical markdown."""

from __future__ import annotations

import os
import warnings
from datetime import UTC, date, datetime
from importlib.metadata import PackageNotFoundError, version

from luvoire.export.odd.odd_schema import TODO_STUB, OddReport

REFERENCE = "Grimm et al. 2020, JASSS 23(2) 7."


def render_markdown(report: OddReport) -> str:
    if any(section.strip() == TODO_STUB for _, section in report.section_items()):
        warnings.warn(
            "ODD report contains TODO stubs; author-authored sections remain incomplete.",
            UserWarning,
            stacklevel=2,
        )
    lines = [
        "# ODD Protocol Description",
        "",
        f"Generated by Luvoire v{_luvoire_version()} on {_generated_on(report)}.",
        f"Reference: {REFERENCE}",
        "",
    ]
    for index, (title, body) in enumerate(report.section_items(), start=1):
        lines.extend(
            [
                f"## {index}. {title}",
                "",
                body.strip(),
                "",
            ]
        )
    return "\n".join(lines).rstrip() + "\n"


def _generated_on(report: OddReport) -> str:
    if report.generated_on:
        return report.generated_on
    explicit = os.environ.get("LUVOIRE_ODD_GENERATED_ON")
    if explicit:
        return explicit
    source_date_epoch = os.environ.get("SOURCE_DATE_EPOCH")
    if source_date_epoch:
        return datetime.fromtimestamp(int(source_date_epoch), tz=UTC).date().isoformat()
    return date.today().isoformat()


def _luvoire_version() -> str:
    try:
        return version("luvoire-engine")
    except PackageNotFoundError:
        return "0.3.0"


__all__ = ["REFERENCE", "render_markdown"]
