"""Build the consolidated Knoema attribution artifact."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "ATTRIBUTIONS.md"


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if ATTRIBUTIONS.md is stale")
    args = parser.parse_args(argv)

    rendered = render_attributions(ROOT)
    if args.check:
        if not OUTPUT.exists():
            raise SystemExit("ATTRIBUTIONS.md is missing; run scripts/build_attributions.py")
        current = OUTPUT.read_text(encoding="utf-8")
        if current != rendered:
            raise SystemExit("ATTRIBUTIONS.md is stale; run scripts/build_attributions.py")
        return

    OUTPUT.write_text(rendered, encoding="utf-8", newline="\n")


def render_attributions(root: Path) -> str:
    legal = (root / "legal" / "attribution.md").read_text(encoding="utf-8")
    lines = [
        "# Knoema Attributions",
        "",
        "Generated by `python scripts/build_attributions.py`. Edit the source files, not this file.",
        "",
        "## Nemotron",
        "",
        "- License summary: CC-BY-4.0 / `cc-by-4.0`.",
        *_extract_legal_section(legal, "Nemotron-Personas-Korea"),
        "",
        *_quoted_file(root / "LICENSE-NEMOTRON.md"),
        "",
        "## CAT-28",
        "",
        *_quoted_file(root / "demo" / "replay" / "profiles" / "personality_cat28" / "CITATION.md"),
        "",
        "## Criminology Research",
        "",
        *_research_appendices(root),
        "",
        "### YAML literature_sources",
        "",
        *_yaml_literature_sources(root),
        "",
        "## Third-Party Libraries",
        "",
        *_extract_legal_section(legal, "Third-Party Libraries"),
        "",
        "## Patent & Trademark Notices",
        "",
        *_extract_legal_section(legal, "Patent and Trademark Notices"),
        "",
    ]
    return "\n".join(lines)


def _quoted_file(path: Path) -> list[str]:
    rel = path.relative_to(ROOT).as_posix()
    text = path.read_text(encoding="utf-8").strip()
    return [f"### {rel}", "", "```text", text, "```"]


def _research_appendices(root: Path) -> list[str]:
    research_root = root / "demo" / "replay" / "profiles" / "_research"
    output: list[str] = ["### Research citation appendices", ""]
    for path in sorted(research_root.rglob("*_research.md")):
        appendix = _citation_appendix(path.read_text(encoding="utf-8"))
        if not appendix:
            continue
        rel = path.relative_to(root).as_posix()
        output.extend([f"#### {rel}", "", "```text", appendix, "```", ""])
    return output[:-1] if output[-1] == "" else output


def _citation_appendix(text: str) -> str:
    marker = "## Citation appendix"
    lower = text.lower()
    index = lower.find(marker.lower())
    if index < 0:
        return ""
    appendix = text[index + len(marker) :].strip()
    return "\n".join(line.rstrip() for line in appendix.splitlines()).strip()


def _yaml_literature_sources(root: Path) -> list[str]:
    profiles_root = root / "demo" / "replay" / "profiles"
    rows: list[tuple[str, str]] = []
    for path in sorted(profiles_root.rglob("*.yaml")):
        if path.name == "schema.yaml":
            continue
        payload = yaml.safe_load(path.read_text(encoding="utf-8"))
        if not isinstance(payload, dict):
            continue
        sources = payload.get("literature_sources")
        if not isinstance(sources, list):
            continue
        rel = path.relative_to(root).as_posix()
        for source in sources:
            if isinstance(source, dict):
                rows.append((rel, _source_line(source)))
    output: list[str] = []
    for rel, line in sorted(rows):
        output.append(f"- `{rel}`: {line}")
    return output


def _source_line(source: dict[str, Any]) -> str:
    parts: list[str] = []
    for key in ("author", "year", "title", "doi", "isbn", "issn"):
        value = source.get(key)
        if value is not None:
            parts.append(f"{key}={value}")
    return "; ".join(parts)


def _extract_legal_section(text: str, heading: str) -> list[str]:
    lines = text.splitlines()
    start = None
    for index, line in enumerate(lines):
        if line.strip() == f"## {heading}":
            start = index + 1
            break
    if start is None:
        raise SystemExit(f"legal/attribution.md missing section: {heading}")
    section: list[str] = []
    for line in lines[start:]:
        if line.startswith("## "):
            break
        section.append(line.rstrip())
    while section and section[0] == "":
        section.pop(0)
    while section and section[-1] == "":
        section.pop()
    return section


if __name__ == "__main__":
    try:
        main()
    except BrokenPipeError:
        sys.exit(1)
