"""Luvoire: deterministic multi-agent simulation engine.

Copyright (c) 2026 Celovin. MIT License.
"""

from luvoire.benchmark import (
    BenchmarkConfig,
    BenchmarkReport,
    BenchmarkRun,
    ComparisonRow,
    build_comparison_rows,
    build_village_personas,
    format_markdown_report,
    run_luvoire_benchmark,
)
from luvoire.cognition import (
    LearnedSkill,
    Monologue,
    MonologueGenerator,
    ObservedBehavior,
    SocialLearner,
)
from luvoire.community import CommunityScenario, seed_community_scenarios
from luvoire.config import LuvoireConfig, load_config
from luvoire.decision import DecisionEngine, decide
from luvoire.distributed import (
    BackendRunSummary,
    DistributedSimulationConfig,
    RayExecutor,
    Shard,
    ShardPlan,
    detect_hot_shards,
    rebalance_hot_shards,
    shard_agents_by_location,
)
from luvoire.dsl import (
    EnvironmentSpecV2,
    EthicsSpecV2,
    ParameterSpec,
    Scenario,
    ScenarioV2,
    TierAParam,
    TierBParam,
    TierCParam,
    load_scenario,
    load_scenario_v2,
)
from luvoire.emotion import EmotionState, EmotionStimulus
from luvoire.environment import Environment, EnvironmentContext
from luvoire.evaluation import (
    ComparisonPair,
    EvaluationSession,
    ReliabilityReport,
    TraceCriterionScore,
    TraceGradeReport,
    cohen_kappa,
    compute_inter_rater_reliability,
    fleiss_kappa,
    grade_trace_report,
)
from luvoire.export import (
    export_finetuning_jsonl,
    export_run_log_parquet,
    flatten_run_log,
    query_run_parquet,
    to_anthropic_jsonl,
    to_dpo_pairs,
    to_openai_jsonl,
)
from luvoire.game import NPC, GameSession, NPCResponse
from luvoire.llm import (
    AnthropicClient,
    CachedLLMClient,
    LlamaCppClient,
    LLMCacheStats,
    LLMCallRecord,
    LLMGateway,
    LocalClient,
    LocalLLMError,
    OllamaClient,
    OpenAIClient,
    VLLMClient,
)
from luvoire.memory import (
    HashEmbeddingEncoder,
    MemorySearchResult,
    MemorySummarizer,
    RetrievalWeights,
    ShortTermMemoryBuffer,
    SQLiteFaissMemoryStore,
)
from luvoire.metrics import compute_pcs, compute_rcs, score_log
from luvoire.persona import Persona
from luvoire.planning import AgentContext, HierarchicalPlanner, Task, WorldState
from luvoire.prompts import (
    SUPPORTED_PROMPT_LANGUAGES,
    PromptLanguage,
    normalize_prompt_language,
    render_decision_user_prompt,
    render_persona_system_prompt,
)
from luvoire.protocols import LLMClient, MemoryRetriever, MemoryWriter, PromptRenderable
from luvoire.relationship import InteractionOutcome, Relationship, RelationshipGraph
from luvoire.reproducibility import (
    VerificationReport,
    generate_run_fingerprint,
    result_merkle_root,
    verify_run_fingerprint,
)
from luvoire.safety import (
    COMMERCIAL_AUDIT_EVENT_TYPES,
    AuditEvent,
    AuditLog,
    AuditLogWriter,
    ContentFilter,
    FilterDecision,
    NoOpAuditLog,
    SafetyCategory,
    audit_event_from_record,
    validate_audit_record,
    validate_commercial_audit_record,
)
from luvoire.scaling import CityScaleConfig, CityScaleResult, CityScaleRunner
from luvoire.simulator import SimulationLogEntry, Simulator
from luvoire.telemetry import (
    NullTelemetryClient,
    TelemetryClient,
    TelemetryEvent,
    TelemetrySettings,
    build_cli_properties,
    build_env_telemetry_client,
    load_or_create_anonymous_id,
    telemetry_opt_in_from_env,
)
from luvoire.theory_of_mind import (
    SallyAnneBenchmarkResult,
    SallyAnneCaseResult,
    TheoryOfMindContext,
    TheoryOfMindEngine,
    TheoryOfMindProfile,
    run_sally_anne_benchmark,
)
from luvoire.types import (
    Action,
    AgentID,
    Emotion,
    Memory,
    MemoryType,
    Personality,
    RelationshipType,
    WorldEvent,
)

__version__ = "0.3.0"
__author__ = "Celovin"
__license__ = "MIT"
__pronounces__ = "/lu?.vw??r/"
__korean_name__ = "猷⑤??꾨Ⅴ"

__all__ = [
    "COMMERCIAL_AUDIT_EVENT_TYPES",
    "NPC",
    "SUPPORTED_PROMPT_LANGUAGES",
    "Action",
    "AgentContext",
    "AgentID",
    "AnthropicClient",
    "AuditEvent",
    "AuditLog",
    "AuditLogWriter",
    "BackendRunSummary",
    "BenchmarkConfig",
    "BenchmarkReport",
    "BenchmarkRun",
    "CachedLLMClient",
    "CityScaleConfig",
    "CityScaleResult",
    "CityScaleRunner",
    "CommunityScenario",
    "ComparisonPair",
    "ComparisonRow",
    "ContentFilter",
    "DecisionEngine",
    "DistributedSimulationConfig",
    "Emotion",
    "EmotionState",
    "EmotionStimulus",
    "Environment",
    "EnvironmentContext",
    "EnvironmentSpecV2",
    "EthicsSpecV2",
    "EvaluationSession",
    "FilterDecision",
    "GameSession",
    "HashEmbeddingEncoder",
    "HierarchicalPlanner",
    "InteractionOutcome",
    "LLMCacheStats",
    "LLMCallRecord",
    "LLMClient",
    "LLMGateway",
    "LearnedSkill",
    "LlamaCppClient",
    "LocalClient",
    "LocalLLMError",
    "LuvoireConfig",
    "Memory",
    "MemoryRetriever",
    "MemorySearchResult",
    "MemorySummarizer",
    "MemoryType",
    "MemoryWriter",
    "Monologue",
    "MonologueGenerator",
    "NPCResponse",
    "NoOpAuditLog",
    "NullTelemetryClient",
    "ObservedBehavior",
    "OllamaClient",
    "OpenAIClient",
    "ParameterSpec",
    "Persona",
    "Personality",
    "PromptLanguage",
    "PromptRenderable",
    "RayExecutor",
    "Relationship",
    "RelationshipGraph",
    "RelationshipType",
    "ReliabilityReport",
    "RetrievalWeights",
    "SQLiteFaissMemoryStore",
    "SafetyCategory",
    "SallyAnneBenchmarkResult",
    "SallyAnneCaseResult",
    "Scenario",
    "ScenarioV2",
    "Shard",
    "ShardPlan",
    "ShortTermMemoryBuffer",
    "SimulationLogEntry",
    "Simulator",
    "SocialLearner",
    "Task",
    "TelemetryClient",
    "TelemetryEvent",
    "TelemetrySettings",
    "TheoryOfMindContext",
    "TheoryOfMindEngine",
    "TheoryOfMindProfile",
    "TierAParam",
    "TierBParam",
    "TierCParam",
    "TraceCriterionScore",
    "TraceGradeReport",
    "VLLMClient",
    "VerificationReport",
    "WorldEvent",
    "WorldState",
    "__korean_name__",
    "__pronounces__",
    "__version__",
    "audit_event_from_record",
    "build_cli_properties",
    "build_comparison_rows",
    "build_env_telemetry_client",
    "build_village_personas",
    "cohen_kappa",
    "compute_inter_rater_reliability",
    "compute_pcs",
    "compute_rcs",
    "decide",
    "detect_hot_shards",
    "export_finetuning_jsonl",
    "export_run_log_parquet",
    "flatten_run_log",
    "fleiss_kappa",
    "format_markdown_report",
    "generate_run_fingerprint",
    "grade_trace_report",
    "load_config",
    "load_or_create_anonymous_id",
    "load_scenario",
    "load_scenario_v2",
    "normalize_prompt_language",
    "query_run_parquet",
    "rebalance_hot_shards",
    "render_decision_user_prompt",
    "render_persona_system_prompt",
    "result_merkle_root",
    "run_luvoire_benchmark",
    "run_sally_anne_benchmark",
    "score_log",
    "seed_community_scenarios",
    "shard_agents_by_location",
    "telemetry_opt_in_from_env",
    "to_anthropic_jsonl",
    "to_dpo_pairs",
    "to_openai_jsonl",
    "validate_audit_record",
    "validate_commercial_audit_record",
    "verify_run_fingerprint",
]
